import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  logoArea:{
    width: '80%',
    height:'16%',
    justifyContent:'center',
    alignItems: 'center',
  },
  logo:{
    width: '100%',
    height: '100%',
  },
  inputArea:{
    width: '80%',
    height: '30%',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  inputTxt:{
    backgroundColor: "#EFFCF6",
    borderRadius: 10,
    width: '100%',
    height: 60,
    padding: 15,
    placeholderTextColor: '#829AB1',
  },
  forgotPswArea:{
    width: '100%',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  forgotPsw:{
    width: '60%',
    height: 19,
    color: '#0C008C',
    fontWeight: 400,
    fontSize: 16,
  },
  singInArea:{
    width: '100%',
    height: 150,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  singIn:{
    width: '80%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0C008C',
    borderRadius: 20, 
  },
  singInBtn:{
    fontWeight: 400,
    fontSize: 16,
    color: '#F0F4F8', 
    letterSpacing: 2,
  },
  registerArea:{
    width: '60%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EFFCF6',
    borderRadius: 20,
    borderColor: '#0C008C',
    borderWidth: 2,
  },
  registerBtn:{
    fontWeight: 400,
    fontSize: 16,
    color: '#0C008C', 
  },
  profissionalArea:{
    width: '100%',
    height: 80,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    textAlign: 'center',
  },
  profissionalText:{
    color: '#0C008C',
    fontWeight: 400,
    fontSize: 16,
    marginBottom: 5,
  },
  profissionalBtnArea:{
    width: '35%',
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EFFCF6',
    borderRadius: 20,
    borderColor: '#0C008C',
    borderWidth: 2,
  },
  profissionalBtn:{
    fontWeight: 400,
    fontSize: 16,
    color: '#1D0EBE',
  },
});
